query GetWestendHistoryElements(
    $pageCount: Int!
    $cursor: Cursor!
    $address: String!
    $orderBy: [HistoryElementsOrderBy!]
) {
    historyElements(
        after: $cursor
        first: $pageCount
        orderBy: $orderBy
        filter: {
            address: { equalTo: $address }
        }
    ) {
        pageInfo {
            endCursor
            hasNextPage
        }
        nodes {
            id @catch(to: NULL)
            timestamp @catch(to: NULL)
            address @catch(to: NULL)
            reward @catch(to: NULL)
            transfer @catch(to: NULL)
            extrinsic @catch(to: NULL)
        }
    }
}