query GetAssetsInfo(
    $pageCount: Int!,
    $cursor: Cursor!,
    $tokenIds: [String!]
    $timestamp: Int!
) {
    entities:
        assets(
            first: $pageCount
            after: $cursor
            filter: {
                and: [
                    {
                        id: {
                            in: $tokenIds
                        }
                    }
                ]
            }
        ) {
            nodes {
                id @catch(to: NULL)
                liquidity @catch(to: NULL)
                hourSnapshots:
                    data(
                        orderBy: TIMESTAMP_DESC
                        filter: {
                            and: [
                                {
                                    timestamp: {
                                        greaterThanOrEqualTo: $timestamp
                                    }
                                }
                                {
                                    type: {
                                        equalTo: HOUR
                                    }
                                }
                            ]
                        }
                    ) {
                        nodes {
                            priceUSD @catch(to: NULL)
                        }
                    }
            }
            pageInfo {
                hasNextPage
                endCursor
            }
        }
}