query GetAssetsInfo(
    $cursor: Cursor!,
    $tokenIds: [String!]
) {
    data:
        assets(
            after: $cursor
            filter: {
                and: [
                    {
                        id: {
                            in: $tokenIds
                        }
                    }
                ]
            }
        ) {
            edges {
                node {
                    id @catch(to: NULL)
                    liquidity @catch(to: NULL)
                    priceChangeDay @catch(to: NULL)
               }
            }
            pageInfo {
                hasNextPage
                endCursor
            }
        }
}